### Randomness

In [2]:
# For generating numbers.
import numpy as np

# Flip a fair coin.
np.random.binomial(1, 0.5)

1

In [3]:
# Repeated flips
# Flip a fair coin 100 times.
np.random.binomial(1, 0.5, 100)

array([1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1])

In [4]:
# Flip a fair coin 100 times, giving only the total number of heads.
np.random.binomial(100, 0.5)

59

In [5]:
# 10 coin flips
# Keep flipping coins until we get three examples of getting five heads in ten coin tosses.

# Number of examples.
N = 3

# Keep track of number of arrays generated.
total_no = 0

# Keep trying until we get three examples.
while N > 0:
    # Add 1 to total.
    total_no = total_no + 1
    # Toss 10 coins.
    tosses = np.random.binomial(1, 0.5, 10)
    # Check if we got five heads.
    if tosses.sum() == 5:
        # If we got 5 heads, print the list of heads/tails.
        print(tosses)
        # Reduce the number of examples left to find by 1.
        N = N - 1

print(f'Total generated: {total_no}')

[0 0 1 0 0 1 0 1 1 1]
[0 0 1 0 1 0 1 0 1 1]
[0 0 1 0 0 0 1 1 1 1]
Total generated: 14


In [6]:
# Counting heads
(10 * 9 * 8 * 7 * 6) // (5 * 4 * 3 * 2 * 1)

252

In [7]:
# Possibilities for positions of the first and second 1's
# Number of combinations.
no_combs = 0

# Select the first position.
for first in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
    # Select the position for the second position.
    for second in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
        # Make sure the first and second positions are different.
        if not first == second:
            # Print the combination.
            print(f'({first:2},{second:2})')
            # Add one to number of combinations.
            no_combs = no_combs + 1

# Print total number of combinations.
print(f'Total combinations is {no_combs}.')

( 1, 2)
( 1, 3)
( 1, 4)
( 1, 5)
( 1, 6)
( 1, 7)
( 1, 8)
( 1, 9)
( 1,10)
( 2, 1)
( 2, 3)
( 2, 4)
( 2, 5)
( 2, 6)
( 2, 7)
( 2, 8)
( 2, 9)
( 2,10)
( 3, 1)
( 3, 2)
( 3, 4)
( 3, 5)
( 3, 6)
( 3, 7)
( 3, 8)
( 3, 9)
( 3,10)
( 4, 1)
( 4, 2)
( 4, 3)
( 4, 5)
( 4, 6)
( 4, 7)
( 4, 8)
( 4, 9)
( 4,10)
( 5, 1)
( 5, 2)
( 5, 3)
( 5, 4)
( 5, 6)
( 5, 7)
( 5, 8)
( 5, 9)
( 5,10)
( 6, 1)
( 6, 2)
( 6, 3)
( 6, 4)
( 6, 5)
( 6, 7)
( 6, 8)
( 6, 9)
( 6,10)
( 7, 1)
( 7, 2)
( 7, 3)
( 7, 4)
( 7, 5)
( 7, 6)
( 7, 8)
( 7, 9)
( 7,10)
( 8, 1)
( 8, 2)
( 8, 3)
( 8, 4)
( 8, 5)
( 8, 6)
( 8, 7)
( 8, 9)
( 8,10)
( 9, 1)
( 9, 2)
( 9, 3)
( 9, 4)
( 9, 5)
( 9, 6)
( 9, 7)
( 9, 8)
( 9,10)
(10, 1)
(10, 2)
(10, 3)
(10, 4)
(10, 5)
(10, 6)
(10, 7)
(10, 8)
(10, 9)
Total combinations is 90.


In [9]:
# Every outcome is counted twice; 
# We need to divide the 90 by 2, to get 45 distinct placements of the first two 1's
90 // 2

45

In [10]:
# There are 45 ways to get two heads, and 252 ways to get five heads.
# There are two possibilities for the first flip, and two for the second, and two for the third, and so on
# To calculate all the possibilites - there are 2 to the power of 10 possible results in flipping a coin ten times
2**10

1024

#### Exercise 1

_It is somewhat interesting that (5 * 4 * 3 * 2 * 1) perfectly divides (10 * 9 * 8 * 7 * 6) - there's no remainder.
If we only wanted exactly four heads as opposed to five, the equivalent calculation would be (10 * 9 * 8 * 7) / (4 * 3 * 2 * 1).
Does that evenly divide too? What is the formula in general?
Does it always come out as a positive whole number?_

In this case we are using formula for the **binomial coefficient**:  
    
**${n\choose k}=\frac{n!}{k!(n-k)!}$**  

It refers to a number of possible ways or combinations to choose wanted number of cases k from the total n or **n choose k**.  
In our example we are choosing four heads (k) out of 10 coin flips (n).  

Using the above formula with factorials we get:  
    
${10\choose 4}=\frac{10!}{4!(10-4)!}=\frac{10!}{4!6!}=\frac{10 * 9 * 8 * 7 * 6!}{4!6!}=\frac{10 * 9 * 8 * 7}{4 * 3 * 2 * 1}=\frac{5040}{24}$ = 210  

That means there are 210 possible ways to choose 4 heads out of 10 coin flips.  

We are refering only to the possible number of outcomes of getting four heads, not their order which is implied in the definition of binomial coefficient or the **combination**.  
Otherwise, we would be using **permutation** to find out the order of the possible outcomes.  

#### Exercise 2
_Note that there are the same number of ways to get 4 tails as there to get 4 heads. Explain why this is._  

Since we are calculating how many ways or combinations there are to get 4 heads or 4 tails, it's not important how we call them,
doesn't matter if it's heads or tails, the equation is giving us four out of ten cycles either way.

In [9]:
# We can show it with the math.comb method
import math
# anyfour = math.comb(n, k)
anyfour = math.comb(10, 4)
anyfour

210

In [12]:
# Or by importing scipy.special function
import scipy.special
# exact = True to get the integer
anyfour = scipy.special.comb(10, 4, exact = True)
anyfour

210

#### References:
 * GeeksforGeeks, (2020). Python - math.comb() method, https://www.geeksforgeeks.org/python-math-comb-method/  
 * Mathematical Explorations (2020, August, 6). Binomial Coefficients in LaTeX [Video file]. YouTube. https://www.youtube.com/watch?v=6Zf5spwf4xc  
 * Mcloughlin, I., (2022). GitHub repository, https://github.com/ianmcloughlin/2223-S1-fund-data-analysis/blob/main/notebooks/02-randomness.ipynb   
 * SciPy documentation. Version 1.9.3 (2022). scipy.special.comb, https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.comb.html?highlight=comb    
 * Weisstein, E.W., (n.d.). Binomial Coefficient, https://mathworld.wolfram.com/BinomialCoefficient.html    